[job]
exp_name = "cogvideo-mlp-30s"

[model]
name = "cogvideo"
size = "5B"
ssm_layer = "ttt_mlp"
ttt_base_lr = 0.1
mini_batch_size = 64
video_length = "30sec"

[optimizer]
name = "AdamW"
lr = 1e-5
lr_ssm = 1e-5
lr_end = 1e-5
lr_schedule = "linear"
lr_ssm_schedule = "cosine"
gradient_clipping_norm = 0.1

[training]
global_batch_size = 64
grad_accum_steps = 1
warmup_steps = 50
steps = 2000
adapter_method = "qkvo"
dataset_path = ""
jsonl_paths = "/home/user/ttt_video_dataset/data/jsonl_entry/updated_30s.jsonl"

[remat]
transformer_checkpoint_layer_group_size = 2
scan_checkpoint_group_size = 16
attention = true
forward_ssm = true
reverse_ssm = true
mlp = true

[parallelism]
fsdp_unsharded_dtype = 'bfloat16'
dp_replicate = 16
dp_sharding = 4
tp_sharding = 2

[checkpoint]
interval = 25

[wandb]
project = "cogvideo_release"
entity = "ttt-vid"
log_interval = 1
