[job]
exp_name = "cogvideo-mlp-3s"

[model]
name = "cogvideo"
size = "5B"
ssm_layer = "ttt_mlp"
ttt_base_lr = 0.1
mini_batch_size = 64
video_length = "3sec"

[optimizer]
name = "AdamW"
lr = 1e-5
lr_ssm = 1e-4
lr_end = 1e-5
lr_schedule = "linear"
lr_ssm_schedule = "cosine"
gradient_clipping_norm = 0.1

[training]
global_batch_size = 64
grad_accum_steps = 1
warmup_steps = 100
steps = 2000
#adapter_method = "sft"
adapter_method = "qkvo"
dataset_path = ""
jsonl_paths = "../combine_jsonl/en_clips_13.jsonl"

[remat]
transformer_checkpoint_layer_group_size = 1
scan_checkpoint_group_size = 16

[parallelism]
fsdp_unsharded_dtype = 'bfloat16'
dp_replicate = 1
dp_sharding = 2
tp_sharding = 1

[checkpoint]
interval = 200
init_state_dir ="/ttt-video-dit_v2/exp/06-01-ttt-video-3s-BS64-5000steps/checkpoint/step-400/"
#init_state_dir = "/home/user/ttt-video-dit_v1/CogVideoX-2b-sat/CogVideoX-5b_converted/"

[wandb]
project = "cogvideo_release"
entity = "ttt-vid"
log_interval = 1
